### ISSUE TITLE
useExternalState의 setState를 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#100]
### 🔨 Describe

기본 훅인 useState를 사용할 때 이전 값을 참조한 새로운 값을 생성하려면 다음과 같이 콜백함수를 전달하는 방식을 사용한다.

```
const [state, setState] = useState([]);

setState((prevArray) => [...prevArray, "새로운 값"]);
```

현재 개발한 useExternalState에서는 이 기능이 포함되어있지 않아 위와 같은 동작을 수행하려면 최신 값을 가져오는 `getStoreSnapshot` 메서드를 호출해야 하는 문제점이 있다.

### ✅ Tasks

- [x] StateManager 클래스의 setState 메서드의 타입을 수정한다.
- [x] setState를 실행할 때 콜백함수가 전달 되었을 때, 새로운 state가 전달되었을 때를 분기처리하여 처리하도록 수정한다.
- [x] 콜백 함수가 전달되었을 때 인자로 this.state를 전달해준다.
- [x] 이전 값을 참조하기 위해 getStoreSnapShot을 사용했던 부분을 콜백함수 전달로 수정한다.

### 🙋🏻 More

예상 소요 시간: 1시간

**Comment by gabrielyoon7** [comment]
오 이거 필요했는데
