### ISSUE TITLE
jasypt를 사용해 프로퍼티 암호화를 적용한다

### ISSUE THREAD

**Issue by kiarakim** [woowacourse-teams/2023-car-ffeine#11]
### ✨ Describe

Repository에서 CI/CD를 연동해 어플리케이션을 배포해야할 때 중요한 정보들을 안전하게 관리하기 위함입니다.

### ✅ Tasks

- [x] Gradle에 'jasypt-spring-boot-starter' 추가
- [x] Jasypt 설정 정보 추가(yaml 파일 사용)
- [x] Jasypt Config 파일 생성
- [x] 로컬 환경에서 암호화할 프로퍼티 정보를 암호화된 값으로 확인
- [x] 4번에서 확인된 값을 yaml 혹은 properties 파일에 적용
