### ISSUE TITLE
google map을 전달하는 구조를 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#110]
### 🔨 Describe

현재 구글 지도를 생성해 관리하는 방식에 다음과 같은 문제점들이 존재한다.

- 지도 객체를 전역 상태에서 참조하는 방식, Props로 넘겨 받는 방식이 혼재 되어있다.
- 지도를 생성하는 특정 컴포넌트에 대한 의존성이 높은 구조로 되어있다.
- 지도의 로드 이후 동작을 특정 짓기 위해 부득이하게 추가한 분기 처리 부분이 존재한다.

지도를 특정 컴포넌트 내부에서 생성하는 방식이 아닌 store를 생성할 시 초기 값으로 지정하는 방식을 도입하면 앞선 문제들을 모두 해결할 수 있을 것으로 예상됨.

### ✅ Tasks

- [x] google maps api에 지도 렌더링 요청을 보낼 때 필요한 DOM 요소를 추가한다.
- [x] 클로져를 활용해 최초 생성시에만 지도 렌더링 요청을 보내도록 한다.
- [x] googleMap을 Props로 넘겨받는 모든 컴포넌트를 전역 상태에서 googleMap을 참조하는 방식으로 구조를 수정한다.

### 🙋🏻 More

예상 소요 시간: 1시간
