### ISSUE TITLE
현위치 버튼 클릭 시 현위치로 복귀하는 기능을 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#116]
### ✨ Describe

기존에 만들어 둔 `현위치 위치 파악 기능`을 재활용하여 현위치로 복귀하는 버튼을 구현합니다.

### ✅ Tasks

- [x] 확대 / 축소 버튼 위에 현위치로 복귀 버튼을 띄운다.
- [x] 해당 버튼을 누르면 현위치를 알아내어 지도를 이동시킨다.
- [x] 디자인은 고려하지 않는다.

### 🙋🏻 More

예상 소요 시간 : 10분
