### ISSUE TITLE
getStoreSnapshot을 사용하지 않아도 한번에 충전소 정보가 업데이트 되는 이유를 분석한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#120]
### 📝 Describe

현재 각 마커에서 전역 상태를 변경하는 로직이 포함되어 있어 해당 전역 상태를 참조하는 모든 컴포넌트들에서 새로 생성되는 마커의 개수만큼 리렌더링이 발생할 것으로 예상됐습니다.

하지만 실제 렌더링 모습을 보면 모든 상태 변경이 한번에 이루어짐을 확인해볼 수 있었습니다. 예상치 못한 동작 결과임으로 확실한 원인 파악이 필요합니다.

### ✅ Tasks

- [x] useSyncExternalStore 훅으로 인해 발생한 현상인지 확인해본다.
- [x] recoil, useState, zustand 등 다른 상태 관리 도구에 의해서도 동일하게 동작하는지 확인해본다.
- [x] [React batches state update](https://react.dev/learn/queueing-a-series-of-state-updates#react-batches-state-updates)에 의한 동작인지 확인한다.

### 🙋🏻 More

원인 파악이 완료되면 팀 블로그에 기록하기

**Comment by gabrielyoon7** [comment]
종료 된거임?

**Comment by kyw0716** [comment]
https://round-player-4f2.notion.site/12-useSyncExternalStore-state-67e686eead8b4750b3015a1f75ea3e76?pvs=4

**Comment by kyw0716** [comment]
정확히 어떤 이유인지 찾은듯
