### ISSUE TITLE
충전소 정보 재요청 과정에서 요청이 두 번씩 발생하는 원인을 파악한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#121]
### 📝 Describe

현재 CarFfeineMapListener 컴포넌트 내에서 지도 객체에 바인딩 해준 이벤트들로 인해 드래그, 줌 변화가 발생하면 리액트 쿼리의 mutate 메서드를 호출해 충전소 정보 최신화가 진행됩니다.

이때 요청이 한번 발생할 것으로 예상 됐지만 실제 지도 조작 시 항상 요청이 두 번씩 발생하고 있습니다. 예상치 못한 동작이므로 확실한 원인 파악이 필요합니다.

### ✅ Tasks

- [x] 구조적인 문제로 인해 발생한 현상인지 파악한다.
- [x] 리액트 쿼리 mutate 메서드의 일반적인 동작 방식에 의한 현상인지 파악한다.
- [ ] 개선해볼 수 있다면 어떤 방식으로 진행하면 좋을지 논의해본다.

### 🙋🏻 More

원인 파악이 완료되면 팀 블로그에 기록하기

**Comment by gabrielyoon7** [comment]
원인 파악 완료~~

### 파악 결과

useMutation --> useQuery 순으로 어떤 동작을 일으킬 때에는 동일한 fetch 함수를 사용하지 않습니다.

**Comment by gabrielyoon7** [comment]
오늘 통합 테스트에 문제가 있어서 급한 버그만 제거하고 이후에 이슈 새로 여는 것으로 하겠습니다.
