### ISSUE TITLE
특정 줌 레벨까지 마커의 크기를 줄여서 보여주는 기능을 구현한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#157]
### ✨ Describe

많은 마커들이 한번에 보여지는 경우에 마커의 크기를 줄여 겹쳐서 보이는 경우를 최대한 줄이는 기능을 구현한다.

### ✅ Tasks

- [ ] 줌 레벨이 16 이상 17 미만일 경우 마커의 크기를 줄여서 보여준다.
- [ ] 줌 레벨이 17 이상이 될 경우 기존의 CarffeineMarker를 보여준다.
- [ ] 줌 레벨의 변화를 감지해 줌 레벨의 변화에 따라 두 마커 종류를 선택하도록 한다.
- [ ] 기존의 마커 영역 캐싱 기능을 해치지 않도록 기능을 구현한다.

### 🙋🏻 More
6시간

**Comment by gabrielyoon7** [comment]
# 참고문서

- [Google Maps API 문서](https://developers.google.com/maps/documentation/javascript/marker-clustering)
- [공식 레퍼런스](https://googlemaps.github.io/js-markerclusterer/)
- [공식 레포지토리](https://github.com/googlemaps/js-markerclusterer)

- [예제 1](https://googlemaps.github.io/js-markerclusterer/public/defaults/)
- [예제 2](https://googlemaps.github.io/js-markerclusterer/public/algorithms/)
- [예제 3](https://googlemaps.github.io/js-markerclusterer/public/renderers/)
