### ISSUE TITLE
리스트 스타일 컴포넌트를 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#172]
### ✨ Describe

리스트를 관리할 컴포넌트를 구현합니다.

### ✅ Tasks

- [x] List 컴포넌트를 구현한다
    - [x] 기본 태그는 ul이다
    - [x] 전체 padding을 줄 수 있다
- [x] ListItem 컴포넌트를 구현한다
    - [x] 호버링 스타일을 구현한다
    - [x] 기본적으로 padding이 존재한다
    - [x] 선긋기 기능을 켤 수 있다

### 🕰️ Estimated Time of Completion

2시간
