### ISSUE TITLE
서버에서 충전소 정보들을 필터링 하는 기능을 만든다

### ISSUE THREAD

**Issue by sosow0212** [woowacourse-teams/2023-car-ffeine#176]
### ✨ Describe

서버에서 충전소 정보를 필터링 하는 기능을 만듭니다.

프론트엔드에서 대부분 필터링을 하나, 한 번 선택하면 잘 바뀌지 않는 필터 정보는 서버에서 제공해주는 것이 효율적입니다.

따라서 프론트엔드에서 요청하는 정보에 대한 필터 기능을 서버에서 만듭니다.

### ✅ Tasks

- [ ] 외부인이 사용 가능한지
- [ ] 커넥트 타입은 무엇인지
- [ ] 충전 속도는 어떤지
- [ ] 회사명은 어떤 것을 골랐는지
- [ ] 필터는 모두 적용될 수도, 안될 수도 있다
- [ ] 데이터베이스 인덱스 설계

### 🕰️ Estimated Time of Completion

2일
