### ISSUE TITLE
서버 필터링 옵션을 선택하는 UI를 구현한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#187]
### ✨ Describe

서버 필터링 옵션을 선택하는 UI를 구현한다.

서버 필터링 옵션은 다음과 같다.

- 회사명
- 충전 속도
- 충전기 타입

각 옵션의 세부 옵션은 다음과 같다.

### 회사명
- 아마노코리아 `AM`
- 부안군 `BA`
- 비긴스 `BG`
- 비케이에너지 `BK`
- 블루네트웍스보타리에너지 `BN`
- 참빛이브이씨 `BT`
- 캐스트프로 `CB`
- 한국 EV 충전서비스센터 `CP`
- 씨티카 `CS`
- 씨어스 `CT`
- 대영채비 `CU`
- 대구환경공단 `DE`
- 대구시 `DG`
- 대유플러스 `DP`
- 에너지플러스 `E0`
- 에바 `EA`
- 이지차저 `EC`
- 에너지파튼즈 `EG`
- 이엔에이치에너지 `EH`
- 이노케이텍 `EK`
- evmost `EM`
- 이엔 `EN`
- 이카플러그 `EP`
- 에버온 `EV`
- 차지인 `EZ`
- 광주시 `G1`
- 광주시 `G2`
- 지커넥트 `GN`
- 군포시 `GP`
- GS 칼텍스 `GS`
- 에이치엘비생명과학 `HB`
- 현대자동차 `HD`
- 한국전기차충전서비스 `HE`
- 에이치엘비일렉 `HL`
- 휴맥스이브이 `HM`
- 홈앤서비스 `HS`
- 한화솔루션 `HW`
- 익산시 `IK`
- 중앙제어 `JA`
- 제주에너지공사 `JC`
- 제주도청 `JD`
- 제주전기자동차서비스 `JE`
- 종하아이앤씨 `JH`
- 전주시 `JJ`
- 제이앤씨플랜 `JN`
- 제주테크노파크 `JT`
- 정읍시 `JU`
- 기아자동차 `KA`
- 한국컴퓨터 `KC`
- 한국전기차인프라기술 `KE`
- 기아자동차 `KI`
- 클린일렉스 `KL`
- 카카오모빌리티 `KM`
- 한국환경공단 `KN`
- 이브이파트너스 `KO`
- 한국전력 `KP`
- 한국전기차솔루션 `KS`
- 케이티 `KT`
- 한국충전연합 `KU`
- 롯데정보통신 `LD`
- LG 헬로비전 `LH`
- 맥플러스 `MA`
- 환경부 `ME`
- 매니지온 `MO`
- 모던텍 `MT`
- 남부솔루션 `NB`
- 에너넷 `NE`
- 나주시 `NJ`
- 한국전자금융 `NT`
- 현대오일뱅크 `OB`
- 파킹클라우드 `PC`
- 차지비 `PI`
- 플러그링크 `PL`
- 이브이파킹서비스 `PS`
- 파워큐브 `PW`
- 렏이엔지 `RE`
- 에스이피 `S1`
- 설악에너텍 `SA`
- 소프트베리 `SB`
- 삼척시 `SC`
- 스칼라데이터 `SD`
- 서울시 `SE`
- 스타코프 `SF`
- SK 시그넷 `SG`
- 세종시 `SJ`
- SK 에너지 `SK`
- 성민기업 `SM`
- 서울에너지공사 `SN`
- 선광시스템 `SO`
- 스마트포트테크놀로지 `SP`
- SK 렌터카 `SR`
- 삼성 EVC `SS`
- 에스트래픽 `ST`
- 태백시 `TB`
- 타디스테크놀로지 `TD`
- 티엘컴퍼니 `TL`
- 티맵 `TM`
- 유니이브이 `UN`
- 울산시 `US`
- 양양군 `YY`

### 충전기 타입

- DC 차데모 `DC_FAST`
- AC 완속 `AC_SLOW`
- DC 차데모+AC3 상 `DC_AC_3PHASE`
- DC 콤보 `DC_COMBO`
- DC 차데모+DC 콤보 `DC_DC_COMBO`
- DC 차데모+AC 상+DC 콤보 `DC_AC_DC_COMBO`
- AC3 상 `AC_3PHASE`

### 충전 속도 (KW/h)

- 3
- 7
- 50
- 100
- 200

### ✅ Tasks

- [ ] 옵션 선택 모달을 여는 트리거를 설정한다.
- [ ] 옵션 선택 모달을 구현한다.
- [ ] 옵션 선택을 완료하면 이후 충전소 정보 조회 요청을 진행할 때 선택한 옵션들을 항상 포함시켜 요청하도록 하는 기능을 구현한다.

### 🕰️ Estimated Time of Completion

5시간
