### ISSUE TITLE
최초 접속 시 토큰을 발급하여 사용자 식별이 가능하도록 한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#198]
### ✨ Describe

아직 로그인 기능이 없으므로 사용자를 식별해줄 임시 토큰을 발급합니다.

### 토큰의 발급 조건
- 최초 접속 시 랜덤한 토큰을 발행합니다.
- 발행된 토큰은 로컬스토리지에 저장됩니다.
- 재접속 시 로컬스토리지에 토큰이 존재한다면 발행하지 않습니다.

### ✅ Tasks

- [x] 토큰 발급을 위해 랜덤한 8자리 정수를 생성합니다.
- [x] 발급된 토큰을 로컬스토리지에 저장합니다.
- [x] 식별 기능이 필요한 경우, 해당 토큰을 활용합니다.
- [x] 재접속 시 로컬스토리지에 토큰이 있는지 없는지 확인하여 재발급 여부를 결정합니다.

### 🕰️ Estimated Time of Completion

1시간
