### ISSUE TITLE
절대 경로를 수정한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#203]
### 🔨 Describe

index 파일로 국한되어 있는 절대 경로가 있어 이를 확장성 있게 수정한다.

### ✅ Tasks

- [x] storybook main에 경로 수정
- [x] jest config 파일에 경로 수정
- [x] webpack config 파일에 경로 수정
- [x] tsconfig 파일에 경로 수정

### 🕰️ Estimated Time of Completion

30분
