### ISSUE TITLE
Box 스타일 컴포넌트를 만든다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#217]
### ✨ Describe

div태그를 대체할 만능 컴포넌트를 만듭니다.

### ✅ Tasks

- [x] padding, margin을 쉽게 조작합니다.
    - [x] x, y, l, r, t, b를 구현한다
    - [x] none을 구현한다
- [x] width, minWidth, maxWidth를 줍니다
- [x] height, minHeight, maxHeight를 줍니다
- [x] css props를 줍니다
- [x] position를 사용할 수 있습니다.
- [x] border를 사용할 수 있습니다.
- [x] backgroundColor를 사용할 수 있습니다.
- [x] color를 사용할 수 있습니다.

### 🕰️ Estimated Time of Completion

1시간
