### ISSUE TITLE
검색창 렌더링 기능을 구현하고 웹 접근성 요소를 추가한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#224]
### ✨ Describe

검색창 렌더링 기능을 구현하고 웹 접근성 요소를 추가한다

### ✅ Tasks

- [x] LNB 돋보기 아이콘 클릭시 StationSearchWindow 컴포넌트 렌더링
- [x] 닫기 버튼 클릭시 StationSearchWindow 사라지는 기능 구현
- [x] 웹 접근성 요소 추가

### 🕰️ Estimated Time of Completion

4시간
