### ISSUE TITLE
모달을 만듭니다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#228]
### ✨ Describe

모달을 만듭시다

### ✅ Tasks

- [x] 바깥에서 상태 주입으로 on/off가 가능한 컴포넌트를 만듭니다.
- [x] 모달은 전역상태로 관리됩니다
- [x] 어떤 내용을 띄워줄지도 바깥에서 결정합니다.

### 🕰️ Estimated Time of Completion

1시간
