### ISSUE TITLE
누적 혼잡도 시각화 컴포넌트의 재사용성을 높인다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#230]
### 🔨 Describe

현재 누적 혼잡도 시각화 컴포넌트는 간단한 변경에도 수정해야 할 곳이 많아져 변경에 불리한 구조를 가지고 있다. 이를 개선해 여러 변경 사항에도 유연하게 대처할 수 있도록 컴포넌트를 수정하는 것이 필요하다.

### ✅ Tasks

- [x] 재사용성을 높이기 위해 리액트 컴파운드 패턴을 적용해 컴포넌트를 설계한다.
  - [x] 상단 메뉴 선택 부분, 하단 그래프 부분을 분리한다.
  - [x] 메뉴 선택, 그래프 컴포넌트에 render props를 사용해 렌더링 할 하위 컴포넌트를 지정할 수 있도록 구성한다.

### 🕰️ Estimated Time of Completion

4시간

### 🙋🏻 More

좀 생소한 방법일 수 있어서 프론트 팀원 형님들과 함께 학습이 필요할 것 같습니다
