### ISSUE TITLE
충전소 상세 정보 조회기능을 개선하고, 누적 고장 신고 확인 기능을 구현한다.

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#238]
### ✨ Describe

누적 고장 신고 기능을 나타내는 기능을 구현하고, 디자인과 로딩 등을 개선합니다.

### ✅ Tasks

- [ ] msw와 api를 최신화하여 누적 고장 신고 수를 다룰 수 있도록 합니다.
- [ ] 받아온 누적 고장 신고 수를 표시합니다.
- [ ] 상세 정보 조회 기능의 디자인을 개선합니다.

### 🕰️ Estimated Time of Completion

2시간
