### ISSUE TITLE
충전기 고장 신고 기능을 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#246]
### ✨ Describe

충전기 상태와 충전소 정보 신고는 분리되어있습니다.
충전기 고장 신고만을 구현합니다.

### ✅ Tasks

- [x] 충전기 고장 신고 버튼을 누르는 경우 서버에 신고가 들어갑니다.
- [x] 한번 신고한 충전기 상태는 다시 신고할 수 없습니다.
- [x] 다시 신고할 수 없도록 버튼이 비활성화 되는 기능도 구현합니다.

### 🕰️ Estimated Time of Completion

2시간
