### ISSUE TITLE
충전소 검색시 해당 충전소 마커로 지도 이동 및 충전소 정보 렌더링하는 기능 구현한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#252]
### ✨ Describe

못다한 충전소 검색 기능을 마저 구현한다

### ✅ Tasks

- [x] 검색어를 입력할 때마다 검색 결과 보여지는 기능 구현
- [x] submit(enter 혹은 돋보기 아이콘 클릭)했을 때 가장 정확도가 높은(첫 번째) 충전소 상세 정보 렌더링 + 마커로 이동 + 간단 정보 렌더링
- [ ] 이동한 곳 주변 충전소 보여주기
- [ ] 사용자가 검색어 입력할 때마다 쿼리를 보낼 수 없으니 언제 쿼리를 보낼지 정확하게 결정하기 ( 글자 입력하고 다음 글자 입력할 때? 디바운스 고려 🤔 급하지 않음 ) 
- [ ] useSyncExternalStore 사용하지 않고 리액트 쿼리로만 전역 관리하는 방향으로 리팩터링 해보기 ( 급하지 않음 )

### 🕰️ Estimated Time of Completion

6시간
