### ISSUE TITLE
아코디언 컴포넌트를 개발한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#266]
### ✨ Describe

현재 좌측 메뉴에서 메뉴들이 점점 펼쳐지는 형태로 자세한 정보를 보여주는 UI를 사용하고 있다. 확장성을 고려한 아코디언 컴포넌트를 구현해 이를 간편하게 대응할 수 있도록 한다.

### ✅ Tasks

- [x] 아코디언 컴포넌트 UI 구상
- [x] 아코디언을 열고 닫는 기능 구현
- [ ] 아코디언에 의해 위치가 바뀌어야 하는 컴포넌트에 대한 대응

### 🕰️ Estimated Time of Completion

5시간
