### ISSUE TITLE
실제 url에 연결하고 development 모드에서 서버를 유동적으로 선택할 수 있도록 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#293]
### 🔨 Describe

현재 localhost에서만 접속이 가능한 상황입니다.
원하는 경우 개발용 api 서버로 연결할 수 있도록 하는 기능을 구현합니다.

### ✅ Tasks

- [ ] production 모드는 수정하지 않습니다.
- [ ] development 모드에서 원하는 서버로 연결이 될 수 있도록 합니다.
   - [ ] 기본 서버는 localhost에 연결되도록 합니다.
   - [ ] 개발용 api 서버에도 연결할 수 있도록 합니다.

### 🕰️ Estimated Time of Completion

1시간
