### ISSUE TITLE
버튼 컴포넌트를 전면 개편한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#314]
### 🔨 Describe

기존의 버튼 디자인이 너무 별로입니다. (사실 디자인이 아예 없음)
버튼 디자인을 싹 갈아 엎고, 좀 더 명시적으로 사용할 수 있는 컴포넌트로 개선 예정입니다.
색상 옵션은 Alert를 기준으로 작성할 예정입니다.
끝

### ✅ Tasks

- [ ] 색상을 선택할 수 있습니다.
- [ ] 아무 옵션을 주지 않아도 기본 템플릿에 적용된 버튼이 보입니다.
- [ ] 버튼의 형태를 제한합니다.
- [ ] 버튼의 css를 해제하는 기능을 구현합니다.

### 🕰️ Estimated Time of Completion

2시간 +@
