### ISSUE TITLE
좌측 메뉴에 의해 마커가 가려지는 문제를 해결한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#332]
### 🔨 Describe

![image](https://github.com/woowacourse-teams/2023-car-ffeine/assets/77326660/b8943e3b-fee6-4939-8c2f-1f45699ec400)

위 이미지와 같이 현재 좌측 메뉴에 의해 마커가 가려지는 현상이 발생했습니다. 간단 정보창의 내용이 보일 수 있도록 지도 이동을 수정해야 할 것 같습니다.

### ✅ Tasks

- [x] 메뉴 펼쳐짐 정도에 따라 달라지는 메뉴 너비 구하기
- [x] 구한 메뉴 너비와 현재 브라우저의 너비의 비율 구하기
- [x] 구한 비율 만큼의 델타 값 구하기
- [x] 구한 델타 값을 지도 중심 이동에 반영하기

### 🕰️ Estimated Time of Completion

5시간
