### ISSUE TITLE
폴더 구조와 파일 이름을 개선한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#360]
### 🔨 Describe

폴더 구조와 파일 이름을 개선한다.

### ✅ Tasks

- [ ] 폴더 구조 개선
- [ ] 파일 이름 명확하게 변경
- [ ] 한 군데에 모여있는 것들 분리
  - [x] 훅 분리
  - [x] 상수 분리
  - [ ] 타입 분리
  - [ ] store 분리

### 🕰️ Estimated Time of Completion

1시간
