### ISSUE TITLE
prettier 3.0 버전으로 올리고 type 절대 경로를 추가한다 

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#371]
### 🔨 Describe

1. `@trivago/prettier-plugin-sort-imports`가 prettier 3.0과 연동되지 않는 문제 때문에 prettier 3.0을 사용하지 못했음. 하지만 `@trivago/prettier-plugin-sort-imports`가 업데이트를 하면서 prettier 3.0을 사용할 수 있게 되어 업그레이드 결정.

2. types 폴더만 절대 경로가 되어 있지 않아 통일성이 깨지고 지저분해 보이는 문제가 있었음 ⇒ types 폴더도 절대 경로 추가

### ✅ Tasks

- [x] `@trivago/prettier-plugin-sort-imports`, `prettier` 최신 버전으로 업데이트
- [x] types 폴더 절대 경로에 추가
  - [x] prettier, webpack, tsconfig, storybook, jest에도 경로 추가 

### 🕰️ Estimated Time of Completion

20분
