### ISSUE TITLE
station, charger, charger status에 id 칼럼을 추가한다

### ISSUE THREAD

**Issue by drunkenhw** [woowacourse-teams/2023-car-ffeine#375]
### 🔨 Describe

현재 id들은 api에서 받아오는 것들입니다 
그래서 저희가 제어할 수 없는 부분에 의존하지 않도록 id 칼럼을 추가합니다

### ✅ Tasks

- [ ] 해당 엔티티에 id 넣기
- [ ] jdbc template로 만든 메서드들 수정하기
- [ ] 연관관계 칼럼 수정하기

### 🕰️ Estimated Time of Completion

5시간
