### ISSUE TITLE
폴더 구조와 파일 이름을 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#382]
### 🔨 Describe

폴더 구조와 파일 이름을 개선한다.

### ✅ Tasks

- [x] 폴더 구조 개선
- [x] 파일 이름 명확하게 변경
- [x] 한 군데에 모여있는 것들 분리
  - [x] 훅 분리
  - [x] 상수 분리
  - [x] 타입 분리
  - [x] store 분리

### 🕰️ Estimated Time of Completion

1시간
