### ISSUE TITLE
로딩중인 화면에 스켈레톤을 적용한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#388]
### ✨ Describe

로딩중인 컴포넌트를 사용자에게 스켈레톤으로 알리는 기능을 구현합니다.

### ✅ Tasks

- [x] 충전소 목록 로딩을 스켈레톤으로 적용한다
- [x] 충전소 상세 정보를 스켈레톤으로 적용한다
    - [x] 충전소 신고 버튼을 스켈레톤으로 적용한다
    - [x] 충전소 통계를 스켈레톤으로 적용한다

### 🕰️ Estimated Time of Completion

2시간
