### ISSUE TITLE
반응형 NavigationBar 컴포넌트를 추가한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#395]
### 🔨 Describe

현재 모바일에서도 웹에서 보여지는 형태 그대로 네비게이션이 보여지는 문제가 있습니다. 화면을 다 가리는 UI들이 있기 때문에 모바일 반응형 디자인을 추가하거나, 모바일에서 보여지는 컴포넌트를 따로 개발해야 할 것 같습니다.

### ✅ Tasks

- [ ] 미디어 쿼리 추가 vs 새로운 컴포넌트 추가 두 방법 중 더 합리적인 방법을 찾는다.
- [ ] 피그마 디자인 시안을 참고해 컴포넌트를 구현한다.
- [ ] 모바일에서 슬라이드 기능을 추가할 수 있을지 고민해본다.

### 🕰️ Estimated Time of Completion

8시간

**Comment by gabrielyoon7** [comment]
갠적으론 새로운 컴포넌트 추가가 DX에 도움이 될 것으로 생각됩니다
