### ISSUE TITLE
간편 로그인 기능을 구현한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#397]
### ✨ Describe

서버에서 구현된 간편 로그인 기능을 클라이언트와 연결한다.

### ✅ Tasks

- [x] 로그인 모달을 구현한다.
- [x] redirect Uri로 들어올 때 토큰 발급 요청을 발생시킨다.
- [x] 필요하다면 react-router-dom 패키지를 이용한다.

### 🕰️ Estimated Time of Completion

10시간...?
