### ISSUE TITLE
충전소의 평균 별점과 리뷰를 조회하는 기능을 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#412]
### ✨ Describe

충전소 상세 페이지에 진입했을 때 평균 별점과 리뷰를 조회하는 기능을 구현합니다. 

### ✅ Tasks

- [x] 충전소 상세 페이지에 진입 시 평균 별점을 확인할 수 있습니다.
- [x] 충전소 상세 페이지에 진입 시 리뷰 목록을 일부만 확인할 수 있습니다.
- [x] 충전소 상세 페이지에 진입 시 리뷰 목록을 모달에서 상세하게 볼 수 있습니다.
    - [x] 리뷰 상세 페이지는 무한스크롤로 전환하기 쉬운 형태로 제작합니다. (데이터 연동 전까지는 더보기 버튼으로 구현합니다.)

### 🕰️ Estimated Time of Completion

5시간
