### ISSUE TITLE
개인화 메뉴 관련 mock api를 추가한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#422]
### ✨ Describe

- 필터링 정보를 보내주는 api
- 유저 정보 조회 api
- 유저 필터링 정보 등록 api
- 유저 필터링 정보 조회 api

### ✅ Tasks

- [x] 필터링 정보를 보내주는 api
- [x] 유저 정보 조회 api
- [x] 유저 필터링 정보 등록 api
- [x] 유저 필터링 정보 조회 api

### 🕰️ Estimated Time of Completion

4시간
