### ISSUE TITLE
지도 관련 기능을 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#433]
### ✨ Describe

지도를 좀 더 효율적으로 제어할 수 있도록 합니다.

### ✅ Tasks

- [x] 지도의 동작 범위를 제한합니다.
- [x] 지도의 축소 범위를 제한합니다.
- [x] 지도의 요청 로직 개선을 시도합니다.

### 🕰️ Estimated Time of Completion

30분
