### ISSUE TITLE
변경된 api 명세에 맞게 구현한 개인화 메뉴 관련 mock api들을 수정한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#444]
### 🔨 Describe

api 명세가 변경되었습니다.

### ✅ Tasks

- [x] GET /filters 수정
- [x] GET /members/filters 수정
- [x] POST /members/filters 수정
- [x] GET /members/me 수정

### 🕰️ Estimated Time of Completion

3시간
