### ISSUE TITLE
차량 선택 관련 mock api와 기능을 구현한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#446]
### ✨ Describe

차량 선택 관련 mock api 구현

### ✅ Tasks

- [x] 서버에 등록된 차량 정보 조회 api
- [x] 차량에 해당하는 필터링 정보 조회 api
- [x] 유저 필터링 정보 등록 api
- [x] #458

### 🕰️ Estimated Time of Completion

4시간
