### ISSUE TITLE
prettier 버전 업데이트 및 수정한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#45]
### ✨ Describe

prettier v2.8 → v3.0으로 버전 업데이트 하고,
import 순서 폴더명 styles → style로 변경  

### ✅ Tasks

- [x] prettier 버전 업데이트
- [x] import 순서 폴더명 styles → style로 변경
- [x] 전체 파일에 적용
