### ISSUE TITLE
차량을 관리하는 기능과, 유저의 차량을 등록할 수 있는 기능을 구현한다

### ISSUE THREAD

**Issue by sosow0212** [woowacourse-teams/2023-car-ffeine#455]
### ✨ Describe

차량을 관리하는 기능과, 유저의 차량을 등록할 수 있는 기능을 구현한다

이를 통해 유저는 자신의 차량 등록을 할 수 있습니다.
또한 자신의 차량과 관련된 필터들을 로드할 수 있습니다.

관리자 페이지에서 [현대, 기아]에 해당하는 차량 정보를 등록할 수 있고, 차량에 해당하는 필터 또한 관리자 페이지에서 등록할 수 있습니다.

### ✅ Tasks

- [ ] 차량 정보를 나타내는 Car 테이블을 만든다 
- [ ] 차량 정보를 저장, 조회하는 기능을 만든다.
- [ ] 차량에 해당되는 filter를 관리하는 CarFilter 테이블과  만든다
- [ ] 관리자 페이지에서 차량에 해당하는 필터를 등록할 수 있는 기능을 만든다
- [ ] 유저의 차량을 등록할 수 있도록 MemberCar 테이블을 만든다
- [ ] 유저의 차량을 등록할 수 있는 기능을 만든다

### 🕰️ Estimated Time of Completion

6시간
