### ISSUE TITLE
전역상태관리 도구를 제작한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#46]
### ✨ Describe

useSyncExternalStore 훅을 활용하여 전역에서 상태를 관리할 수 있도록 하고 바닐라 환경에서도 접근 및 조작이 가능한 기능을 구현한다

### ✅ Tasks

- [x] 상태를 바닐라JS 환경에서 관리할 수 있는 저장소를 만든다
- [x] 원자 단위의 독립적인 상태 저장소를 자동으로 생성하는 함수를 만든다
- [x] recoil에서 사용하는 유용한 커스텀 훅(useRecoilState, useRecoilValue, useSetRecoilState)과 사용법이 같아야 한다
- [x] 바닐라 환경에서도 상태를 조작할 수 있는 기능을 만든다

### 🙋🏻 More

- [참고문서](https://github.com/gabrielyoon7/external-state)
