### ISSUE TITLE
msw로 충전소 데이터를 mocking하는 기능을 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#47]
### ✨ Describe

앞으로의 구현할 지도 기능의 원활한 테스트를 위해 충전소 데이터의 요청/응답 시스템을 만든다

단, 충전소 데이터는 랜덤으로 생성하여 반환하는 기능을 구현한다

### ✅ Tasks

- [x] POST방식의 요청을 하며, 중심위도,중심경도,위도델타, 경도델타를 넘겨주는 기능을 구현한다
- [x] 랜덤으로 생성된 충전소 데이터 수만개를 반환하는 기능을 구현한다
- [x] 충전소 타입을 확정한다
