### ISSUE TITLE
충전소 마커를 디자인한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#476]
### ✨ Describe

충전소 마커를 디자인한다.
마커에 사용 가능한 충전기 개수를 보여준다.
사용 가능한 충전기가 0개일 경우, 빨간색 마커로 표시한다.

### ✅ Tasks

- [x] 충전소 마커 디자인
- [x] 마커에 사용 가능한 충전기 개수 렌더링
- [x] 사용 가능한 충전기가 0개일 경우, 마커 색깔 `red`로 변경

### 🕰️ Estimated Time of Completion

3시간
