### ISSUE TITLE
충전소 검색창 디자인 개선 및 라벨 문구 변경한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#487]
### 🔨 Describe

충전소 검색창 디자인 개선 및 라벨 문구 변경한다

### ✅ Tasks

- [x] 공공 충전소 → 외부인 개방
- [x] 외부 제한 구역 →  외부 제한
- [x] 충전소 검색창 디자인 개선 

### 🕰️ Estimated Time of Completion

30분
