### ISSUE TITLE
충전소 상세정보 디자인을 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#490]
### 🔨 Describe

혼잡도 그래프를 제외한 상세 정보의 모든 디자인을 수정/개선합니다.

변경 내용은 8/14 회의 내용에 따릅니다.

### ✅ Tasks

- [ ] 충전소 상세 정보
- [ ] 충전소 정보 불일치 신고
    - [ ] 패딩 사라진거 복구하기
    - [ ] 모달 들썩들썩 제한하기
- [ ] 충전소 검색 결과 눌렀을 때 줌 레벨 좀 더 높게 주기
- [ ] 모달 디자인 개선하기

### 🕰️ Estimated Time of Completion

3시간
