### ISSUE TITLE
충전소 검색창의 UX를 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#501]
### 🔨 Describe

기존의 검색목록 스켈레톤을 제거하고 로딩 스피너를 추가하여 사용자 경험을 개선합니다.

### ✅ Tasks

- [x] 동적 검색 스켈레톤을 제거한다
- [x] 로딩 중에는 돋보기 아이콘을 스피너로 대체한다
- [x] 검색 새로 요청하기 전에 이 전 데이터 들고 있는 기능 구현

### 🕰️ Estimated Time of Completion

30분
