### ISSUE TITLE
최초 리뷰 요청 페이지를 1에서 0으로 변경하고, 버그를 수정한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#517]
### 🔨 Describe

서버에서 0페이지부터 요청해야 한다고 합니다.

### ✅ Tasks

- [x] 후기를 0페이지부터 요청하도록 합니다.
- [x] 답글을 0페이지부터 요청하도록 합니다.
- [ ] 후기 등록 후, 폼을 초기화 합니다.

### 🕰️ Estimated Time of Completion

15분
