### ISSUE TITLE
빌드 관련 설정을 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#527]
### 🔨 Describe

현재 빌드 속도가 많이 느리므로 빌드 속도 개선을 위해 빌드 관련 설정 및 패키지를 수정해야합니다.

### ✅ Tasks

- [x] 로더 패키지 선택
- [x] 빌드 설정 수정
  - [x] 테스트 코드 제외
  - [x] 스토리북 제외
- [x] dev서버 빌드 모드를 production으로 설정

### 🕰️ Estimated Time of Completion

2시간
