### ISSUE TITLE
충전소 상세 정보 디자인을 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#532]
### 🔨 Describe

상세 정보의 간격을 조정하고, 충전소가 로딩 중임을 스피너를 통해 알립니다

### ✅ Tasks

 - [x] 야미가 주장하는 상세 정보 간격 줄이기 작업 하기
 - [x] 로딩 스피너 추가하기
 - [x] 충전기 접기 기능 구현
 

### 🕰️ Estimated Time of Completion

10분
