### ISSUE TITLE
클라이언트 필터링 컴포넌트를 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#566]
### 🔨 Describe

현재 네비게이션 패널이 열리게 되면 클라이언트 필터링 컴포넌트가 가려지는 문제점이 있어 이를 고쳐야 합니다.

### ✅ Tasks

- [x] 패널의 너비를 ref를 통해 참조하지 않고, 상수화 된 값을 통해 참조하도록 수정한다.
- [x] 열려있는 패널의 개수에 따라 클라이언트 필터링 컴포넌트가 옆으로 이동하도록 수정한다.
- [x] 마커에 띄워지는 간단 정보창 로직도 가능하다면 수정해본다.

### 🕰️ Estimated Time of Completion

2시간
