### ISSUE TITLE
충전소 후기 페이지를 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#577]
### 🔨 Describe

충전소 후기를 일부 개선합니다.

### ✅ Tasks

- [ ] 삭제된 후기 및 답글의 이름에 대한 대응
- [ ] 삭제된 후기 및 답글의 시간에 대한 대응
- [ ] 불필요한 태그 제거
- [ ] 글자 간격 조절

### 🕰️ Estimated Time of Completion

30분
