### ISSUE TITLE
Spring actuator 를 설정한다

### ISSUE THREAD

**Issue by be-student** [woowacourse-teams/2023-car-ffeine#58]
### ✨ Describe

로깅을 위한 api를 외부에 제공하는 역할을 합니다
필수 설정으로 prometheus api 를 허용해주어야 추후 모니터링 구축이 편합니다

### ✅ Tasks

- [ ] actuator 라이브러리 설치
- [ ] 외부에서 접근이 허용되지 않는 포트로 actuator 설정 변경 8082 이상 권장
- [ ] 필수 엔드포인트 열기(prometheus)
