### ISSUE TITLE
자잘한 디자인 개선과 주소에 null값이 오는 경우 처리한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#583]
### 🔨 Describe

자잘한 디자인 개선과 주소에 null값이 오는 경우 처리한다.

### ✅ Tasks

- [x] 자잘한 디자인 개선
- [x] 충전소 주소 null 값이 오는 경우 주소 미확인으로 변경
- [x] 고장 신고는 충전소당 한 번만 할 수 있다는 것을 알림

### 🕰️ Estimated Time of Completion

20분
