### ISSUE TITLE
FE 테스트 코드를 보완한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#618]
### 🔨 Describe

아직 테스트 코드가 작성되지 않은 여러 기능들이 존재합니다. 테스트 할 기능에 대해 더 생각해보고, 추가적인 테스트 코드 작성이 필요할 것 같습니다.

### ✅ Tasks

- [x] ServerStationFilters 컴포넌트
  - [x] ServerStationFilters 컴포넌트가 열리면 useServerStationFilters 훅에서 받아온 정보를 화면에 렌더링 한다.
  - [x] 필터 옵션들을 선택하고 적용하기 버튼을 누르면 선택한 옵션들이 전역 상태에 추가된다.
  - [x] 필터 초기화 버튼을 클릭하면 차량 필터를 제외한 모든 필터 옵션들이 해제된다.
- [x] Navigator 컴포넌트
  - [x] ~~돋보기 버튼을 누르면 StationSearchWindow 컴포넌트가 렌더링 된다.~~ 
  - [x] ~~필터 조정 버튼을 누르면 ServerStationFilters 컴포넌트가 렌더링 된다.~~
    - 렌더링 관련 로직에 구글 지도가 포함되어 있어 테스트 불가능 (테스트 환경에는 window 객체가 존재하지 않음)
  - [x] 멤버 토큰이 없을 때 프로필 버튼을 누르면 로그인 모달이 렌더링 된다. 
  - [x] 멤버 토큰이 있을 때 프로필 버튼을 누르면 프로필 메뉴가 렌더링 된다.
- [x] 프로필 메뉴 컴포넌트
  - [x] 로그아웃 버튼을 클릭하면 저장해두었던 멤버 토큰이 지워진다.
  - [x] 차량 등록 버튼을 클릭하면 차량 선택 모달이 렌더링 된다.

### 🕰️ Estimated Time of Completion

5시간
