### ISSUE TITLE
PWA(웹앱)으로 이용할 수 있도록 한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#634]
### ✨ Describe

PWA(웹앱)으로 이용할 수 있도록 한다

### ✅ Tasks

- [x] PWA에서 사용할 크기별 아이콘 만들기
- [x] 아이콘 html에 추가하기
- [x] android > 앱 설치/현재 페이지 추가 | ios > 홈 화면에 추가 (설치 프롬프트 띄우고 클릭했을 때 바로 다운할 수는 없을까? 🤔)

### 🕰️ Estimated Time of Completion

4시간
