### ISSUE TITLE
혼잡도 관련 코드 리팩토링을 한다

### ISSUE THREAD

**Issue by sosow0212** [woowacourse-teams/2023-car-ffeine#660]
### 🔨 Describe

기존 이슈인 [혼잡도 조회 기능의 성능을 개선한다 #655 ]를 진행하기 앞서 혼잡도 관련 코드를 리팩토링 하고자 합니다.

---

### 버그
먼저 현재 혼잡도 업데이트를 해주는 Repository 로직에 문제가 있습니다.
- totalCount를 +1 해주는 부분에서 추가적으로 SET `use_count / total_count`또한 해주게 됩니다.
그런데 만약 새롭게 생성된 객체라면 `total_count & count == 0`의 기본값을 가지게 됩니다.
이 경우 Division을 하게되면 0/0이 되므로 Mysql에서 Exception이 발생합니다. (작동은 되긴 합니다)

따라서 이 부분의 쿼리를 `CASE WHEN total_count = 0 THEN 0 ELSE use_count / total_count END`와 같이 변경하고자 합니다.

---

### 가독성
현재 혼잡도 관련 코드의 가독성이 좋지 않아서 네이밍과 메서드 분리 및 객체가 할 수 있는 일은 객체가 할 수 있도록 변경하고자 합니다.

---
### 테스트 누락
혼잡도 관련 Repository의 테스트 코드가 누락되어 있습니다.
이 부분을 채우고자 합니다.

### ✅ Tasks

- [ ] Mysql Exception이 터지는 문제 해결
- [ ] 코드 가독성 리팩토링
- [ ] 누락된 테스트 추가

### 🕰️ Estimated Time of Completion

2시간
