### ISSUE TITLE
마커 디자인 및 Layout Shift 개선한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#678]
### 🔨 Describe

마커 디자인을 개선하고 Layout Shift가 최소한으로 일어나도록 한다.

### ✅ Tasks

- [x] 마커 색상 변경 (blue : 578BF2 4F85F1 1A73E8 3373DC 고민)
- [x] 마커 디자인 변경
- [x] 충전기 개수 나타내는 숫자 두껍게 변경

### 🕰️ Estimated Time of Completion

2시간
