### ISSUE TITLE
충전소 마커를 덜 요청하도록 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#695]
### 🔨 Describe

충전소 마커가 너무 자주 요청되는 문제를 수정하기 위해 여러가지 개선 작업을 진행합니다.

### ✅ Tasks

- [x] 델타를 스크린보다 훨씬 크게 잡습니다.
- [x] 마지막 요청 영역을 기록합니다.
- [x] 마지막 요청 영역 내에서의 움직임이라면 재요청을 보내지 않습니다.

### 🕰️ Estimated Time of Completion

1시간
