### ISSUE TITLE
코드 가독성을 증진시킨다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#70]
### 🔨 Describe

1. 포괄적인 파라미터명을 좀 더 명확히 한다.
2. 타입 중복을 없앤다. 

### ✅ Tasks

- [x] map → googleMap 이름 변경
- [x] 타입 중복 제거
- [x] CarFfeineMap 컴포넌트 아래에 CarFfeineMapListener 배치
- [x] useMutation(['stations']) 커스텀 훅으로 분리

### 🙋🏻 More

예상 소요 시간: 30분
