### ISSUE TITLE
msw와 데이터를 개선한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#71]
### 🔨 Describe

msw의 불필요한 경고 메시지를 제거하고, 모킹용 데이터를 현실화 한다

### ✅ Tasks

- [x] msw의 불필요한 경고 메세지 제거
- [x] 모킹용 랜덤 데이터를 현실성 있도록 개선
- [x] 충전소 및 충전기 데이터 타입 현실화

### 🙋🏻 More

예상 소요 시간: 20분
