### ISSUE TITLE
충전소 리스트 정보를 캐싱할 클래스를 구현한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#713]
### ✨ Describe

리스트 정보를 자바스크립트 코드의 객체에서 캐싱할 수 있도록 하는 클래스를 구현합니다.

충전소 id 배열을 통해 각 id에 해당하는 충전소 정보를 불러오는 방식으로 api명세가 변경되어 동일한 충전소 id에 대한 정보 조회 요청이 다수 발생할 여지가 있어 코드 내의 객체에서 이를 관리하도록 결정했습니다.

### ✅ Tasks

- [x] 정보를 저장할 객체의 자료구조를 선택한다.
- [x] 어떤 데이터를 어떤 구조로 저장할지 결정한다.
- [x] 캐싱 정보 등록 메서드를 구현한다.
- [x] 캐싱 정보 삭제 메서드를 구현한다.
- [x] 특정 id값을 포함하고 있는지 판별하는 메서드를 구현한다.

### 🕰️ Estimated Time of Completion

3시간
