### ISSUE TITLE
아이콘을 변경한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#723]
### 🔨 Describe

NavBar 검색 아이콘을 목록 아이콘으로 변경한다.
현재 위치 아이콘을 타겟 아이콘으로 변경한다.

### ✅ Tasks

- [x] NavBar 검색 아이콘을 목록 아이콘으로 변경
- [x] 현재 위치 아이콘을 타겟 아이콘으로 변경
- [x] 모바일에서 클라이언트 필터가 화면 꽉차게 변경

### 🕰️ Estimated Time of Completion

10분
