### ISSUE TITLE
차량 모달 테스트 코드를 추가한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#730]
### ✨ Describe

차량 모달에 대한 테스트 코드가 없어 이를 추가하려 합니다.

### ✅ Tasks

- [ ] 모델명과 연식을 선택한 후 등록 버튼을 클릭하면 다음의 요청들이 발생한다.
  - [ ] 멤버 차량 등록 api 요청
  - [ ] 차량 필터링 정보 조회 api 요청
  - [ ] 멤버 필터링 정보 등록 api 요청
  - [ ] 충전소 조회 api 요청 (새롭게 등록된 필터링 정보들이 request param에 포함되어 요청된다)

### 🕰️ Estimated Time of Completion

2시간
