### ISSUE TITLE
서버로부터 수신 받은 충전소 데이터를 react UI에 목록으로 표시하는 컴포넌트를 구현한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#75]
### ✨ Describe

서버로부터 수신 받은 충전소 데이터를 react UI에 목록으로 표시하는 컴포넌트를 구현한다

### ✅ Tasks

- [x] 디자인이 없는 임의의 컴포넌트에 수신받은 충전소를 목록으로 렌더링 한다
- [x] 렌더링 된 충전소 목록 중 1개를 누르면, 지도에서 해당 위치로 이동한다
- [x] 누른 충전소의 간단 정보가 자동으로 켜진다

### 🙋🏻 More

예상 소요 시간: 2시간
