### ISSUE TITLE
React.lazy() 를 적용하여 code splitting을 적용한다.

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#755]
### 🔨 Describe

비록 이 프로젝트에 페이지가 사실상 존재하지 않지만, 일부 컴포넌트가 초기 로드 시 필요 없는 것으로 파악됩니다.
해당 부분을 찾아 lazy loading 을 적용해줍니다.

### ✅ Tasks

- [x] 충전소 목록을 개선합니다.
- [x] 충전소 상세 보기를 개선합니다.
- [x] 성능 개선 부분을 측정합니다.

### 🕰️ Estimated Time of Completion

1시간
