### ISSUE TITLE
NavBar 디자인을 개선한다

### ISSUE THREAD

**Issue by feb-dain** [woowacourse-teams/2023-car-ffeine#776]
### 🔨 Describe

NavBar UI/UX 개선입니다.

### ✅ Tasks

- [x] 아이콘 색상 변경
- [x] 아이콘 밑에 설명 추가
- [x] 아이폰 navigation bar를 위해 아래 간격 추가  

### 🕰️ Estimated Time of Completion

20분
