### ISSUE TITLE
줌 레벨에 따라 다른 api로 요청이 들어갈 수 있도록 마커 컨테이너를 분리한다

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#809]
### 🔨 Describe

신규 기능으로 제공 될 `저 레벨의 줌 핸들링` 관련하여 대응하는 업데이트 입니다.
기존 로직에 영향이 가지 않으면서 언제든 제거가 가능한 형태로 개발 예정입니다.
다른 코드에 영향이 최소한으로 가도록 분기 처리 예정입니다.

### ✅ Tasks

- [x] 도 단위 요청에 대한 컴포넌트 분리를 선제 대응한다.
- [x] 시 단위의 요청에 대한 컴포넌트 분리를 선제 대응한다.
- [x] 언제든 기존 형태로 복구할 수 있도록 대응한다. 

### 🕰️ Estimated Time of Completion

2시간
