### ISSUE TITLE
충전소 검색 시, 주요 도시도 검색 결과에 포함한다.

### ISSUE THREAD

**Issue by gabrielyoon7** [woowacourse-teams/2023-car-ffeine#825]
### ✨ Describe

충전소 검색 시, 주요 도시도 검색하여 바로 이동할 수 있는 기능을 구현합니다.
단, 주요 도시의 정보가 자주 바뀌지 않는 것을 고려하여 api를 활용하지 않고 클라이언트에서 처리합니다.

### ✅ Tasks

- [ ] 주요 도시의 정보도 충전소 검색 결과에 포함한다.
- [ ] 충전소 검색 결과 최상단에 나오도록 한다.
- [ ] 검색어와 일치하는 단어는 색상을 변경한다.

### 🕰️ Estimated Time of Completion

2시간

**Comment by gabrielyoon7** [comment]
기술적인 문제로 인하여 이 이슈는 닫고 #834로 이전합니다.
