### ISSUE TITLE
마커 렌더링 훅을 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#826]
### 🔨 Describe

현재 마커 렌더링 훅은 특정 마커만을 표시하는 기능을 수행하고 있습니다. 서버 클러스터링이 추가되면서 화면에 표시해야 될 마커의 종류가 많아질 것을 대비해 이 훅을 확장해 다른 마커들도 표시할 수 있도록 하는 것이 좋을 것 같습니다.

### ✅ Tasks

- [ ] 제네릭을 활용해 타입의 확장성을 높인다.
- [ ] 표시할 마커를 외부에서 받아오는 방식으로 변경해 마커 표시 확장성을 높인다.
- [ ] 기존의 기능이 그대로 유지될 수 있도록 한다.

### 🕰️ Estimated Time of Completion

4시간
