### ISSUE TITLE
줌 레벨에 따라 마커 컨테이너를 렌더링 하는 방식을 개선한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#831]
### 🔨 Describe

현재는 줌 레벨에 따라 마커 클러스터링 여부를 결정하는 방식을 사용하고 있습니다. 이 방식을 사용하면 다음과 같은 문제점이 있습니다.

- 모바일에서도 PC와 동일하게 줌 레벨에 따라 마커 클러스터링을 적용하기 때문에 조금만 지도가 축소되어도 마커들이 클러스터링 돼버리는 문제가 있습니다.
- 줌 레벨이 동일한데 너비가 넓은 디바이스를 사용하는 경우 너무 넓은 영역에 대한 요청이 발생해 서버에 큰 부하를 줄 위험성이 있습니다.

따라서 기존 방식에서 델타를 기준으로 마커 클러스터링 여부를 결정하는 방식으로 수정하고자 합니다.

### ✅ Tasks

- [x] 기존의 zoomStore를 deltaStore로 이전한다.
- [x] 적절한 delta 기준을 세운다.
  - [x] delta 면적 기준으로 판별한다.
- [x] 이전 로직을 해치지 않으면서 zoom 기반의 로직을 delta 기준의 로직으로 변경한다.

### 🕰️ Estimated Time of Completion

4시간
