### ISSUE TITLE
지역 검색을 위해서 검색 기능을 리팩토링한다

### ISSUE THREAD

**Issue by sosow0212** [woowacourse-teams/2023-car-ffeine#833]
### ✨ Describe

현재 충전소 이름 검색만 되는데 실제 사용해보니 지역을 통해 검색하는 경우가 필요했습니다.

따라서 검색에서 지역 검색도 되도록 리팩토링합니다

### ✅ Tasks

- [ ] 지역 테이블 추가 및 인덱스 설정
- [ ] flyway 반영
- [ ] 지역 데이터 추가
- [ ] 검색 기능 리팩토링

### 🕰️ Estimated Time of Completion

3시간
