### ISSUE TITLE
영역별 충전소 마커 변경 기준을 더 세분화 한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#852]
### 🔨 Describe

- 델타 영역을 넓힘에 따라서 화면에 더 많은 마커가 그려질 경우가 생겼는데 현재 마커로는 지도를 너무 많이 가리는 문제가 있습니다.
- 마커 크기를 줄이는 방식으로 위 문제를 해결하려 했지만 그렇게 했을 경우 모바일에서 클릭이 어렵다는 문제가 있습니다.

위 두 문제로 인해 영역별 충전소 마커 변경 기준을 더 세분화 하는 것이 좋을 것 같습니다.

### ✅ Tasks

- [ ] 영역 세분화 정도 정하기
- [ ] 점 마커 도입
- [ ] 디폴트 마커 비율 조정
- [ ] 분기 처리 어디서 할지 고민해보기

### 🕰️ Estimated Time of Completion

3시간
