### ISSUE TITLE
서버 클러스터링 mock api를 구현한다

### ISSUE THREAD

**Issue by kyw0716** [woowacourse-teams/2023-car-ffeine#853]
### ✨ Describe

서버 클러스터링이 추가됨에 따라 해당 api에 대한 msw가 필요해졌습니다.

- latitude
- longitude
- latitudeDelta
- longitudeDelta
- latitudeDivisionSize
- longitudeDivisionSize

위 정보를 입력 받아 latitudeDivisionSize * longitudeDivisionSize 개수로 클러스터 mock 데이터를 생성하는 msw를 구현합니다.
입력 받은 정보를 토대로 자체 격자 무늬를 나누어 각 사각형 내부에서 랜덤한 센터 좌표를 구하고, 랜덤한 count를 생성하도록 합니다.

### ✅ Tasks

- [x] 입력 받은 정보를 토대로 지도 위 임의의 사각형을 만들고, 해당 사각형을 격자 무늬로 나눈다.
- [ ] 나뉜 격자 무늬 내부 각 사각형에 랜덤한 센터 좌표를 구한다.
- [ ] 랜덤한 수치를 생성한다. (조금 사실적인 값이면 더 좋을 듯 -> 예: 델타가 클 수록 좀 더 큰 수치를 생성한다)

### 🕰️ Estimated Time of Completion

3시간
