### ISSUE TITLE
무중단 배포를 위해 스크립트를 수정한다

### ISSUE THREAD

**Issue by sosow0212** [woowacourse-teams/2023-car-ffeine#871]
### ✨ Describe

무중단 배포를 위해서 기존 스크립트를 수정합니다

### ✅ Tasks

- [ ] Actuator health-check 열기
- [ ] deploy 스크립트 수정하기
- [ ] 서버 내에서 스크립트 생성하기
