### ISSUE TITLE
검색 기능을 구현한다

### ISSUE THREAD

**Issue by be-student** [woowacourse-teams/2023-car-ffeine#89]
### ✨ Describe

검색 조건은 총 1가지 입니다 
1. 이름 + 주소

### ✅ Tasks

- [ ] 충전소 이름에 대한 Like 검색
- [ ] 충전소 주소에 대한 Like 검색
- [ ] 2개를 통합하는 과정

## 검색 기능 구현 방식

1. Like

### 예상 소요 시간

제이 : 12시간
키아라 : 16시간
박스터 : 13시간
누누 : 10시간

결과 : 13시간
