### ISSUE TITLE
log level error 이상일 경우 slack notification 을 설정한다

### ISSUE THREAD

**Issue by be-student** [woowacourse-teams/2023-car-ffeine#9]
### ✨ Describe

백엔드 로그를 찍었을 때, log level 이 error 단계 이상이라면, 바로 slack 알림을 보내는 기능

### ✅ Tasks

- [ ] 로그 라이브러리 선정
- [ ] slack webhook 등록
- [ ] log level error 단계라면, slack notifiaction 을 발송하도록 설정한다
